language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

sudo: required
jdk:
  - oraclejdk8
install:
  - true

script:
  - ./gradlew test --console verbose -i
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
      - ./gradlew :library:createFullJarRelease
      - ./gradlew :library:exportJar
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_TEMP
  file: "../jars/stream-chat-android.jar"
  skip_cleanup: true
  on:
    tags: true
