name: Android CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare environment
      run: |
        git fetch --unshallow
        echo "${{ secrets.RELEASE_KEYSTORE }}" > sample/.sign/release.keystore.asc
        gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch sample/.sign/release.keystore.asc > sample/.sign/release.keystore
        echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > sample/.sign/keystore.properties.asc
        gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch sample/.sign/keystore.properties.asc > sample/.sign/keystore.properties
    - name: Assemble
      run: bash ./gradlew :sample:assemble --stacktrace
    - name: Upload testDebugUnitTest Results
      uses: actions/upload-artifact@v2
      with:
        name: sample-release
        path: sample/build/outputs/apk/release/
    - name: Upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: stream-testers
        file: sample/build/outputs/apk/release/sample-release.apk

