name: Stream Chat Android CI

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: KtLint
      run: bash ./gradlew :stream-chat-android:ktlintCheck :stream-chat-android-sample:ktlintCheck
    - name: Unit tests
      run: bash ./gradlew :stream-chat-android:test :stream-chat-android-sample:test --stacktrace
    - name: Upload testDebugUnitTest Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: testDebugUnitTest
        path: stream-chat-android/build/reports/tests/testDebugUnitTest
    - name: Upload testDebugUnitTest Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: testReleaseUnitTest
        path: stream-chat-android/build/reports/tests/testReleaseUnitTest

